/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as HomeworkRouteImport } from './routes/homework'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ClassRouteImport } from './routes/class'
import { Route as CircularsRouteImport } from './routes/circulars'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'

const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeworkRoute = HomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassRoute = ClassRouteImport.update({
  id: '/class',
  path: '/class',
  getParentRoute: () => rootRouteImport,
} as any)
const CircularsRoute = CircularsRouteImport.update({
  id: '/circulars',
  path: '/circulars',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/attendance': typeof AttendanceRoute
  '/calendar': typeof CalendarRoute
  '/circulars': typeof CircularsRoute
  '/class': typeof ClassRoute
  '/courses': typeof CoursesRoute
  '/fees': typeof FeesRoute
  '/gallery': typeof GalleryRoute
  '/homework': typeof HomeworkRoute
  '/leave': typeof LeaveRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/timetable': typeof TimetableRoute
  '/transport': typeof TransportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/attendance': typeof AttendanceRoute
  '/calendar': typeof CalendarRoute
  '/circulars': typeof CircularsRoute
  '/class': typeof ClassRoute
  '/courses': typeof CoursesRoute
  '/fees': typeof FeesRoute
  '/gallery': typeof GalleryRoute
  '/homework': typeof HomeworkRoute
  '/leave': typeof LeaveRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/timetable': typeof TimetableRoute
  '/transport': typeof TransportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/attendance': typeof AttendanceRoute
  '/calendar': typeof CalendarRoute
  '/circulars': typeof CircularsRoute
  '/class': typeof ClassRoute
  '/courses': typeof CoursesRoute
  '/fees': typeof FeesRoute
  '/gallery': typeof GalleryRoute
  '/homework': typeof HomeworkRoute
  '/leave': typeof LeaveRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/timetable': typeof TimetableRoute
  '/transport': typeof TransportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/ai-assistant'
    | '/attendance'
    | '/calendar'
    | '/circulars'
    | '/class'
    | '/courses'
    | '/fees'
    | '/gallery'
    | '/homework'
    | '/leave'
    | '/library'
    | '/login'
    | '/messages'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/timetable'
    | '/transport'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/ai-assistant'
    | '/attendance'
    | '/calendar'
    | '/circulars'
    | '/class'
    | '/courses'
    | '/fees'
    | '/gallery'
    | '/homework'
    | '/leave'
    | '/library'
    | '/login'
    | '/messages'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/timetable'
    | '/transport'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/ai-assistant'
    | '/attendance'
    | '/calendar'
    | '/circulars'
    | '/class'
    | '/courses'
    | '/fees'
    | '/gallery'
    | '/homework'
    | '/leave'
    | '/library'
    | '/login'
    | '/messages'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/timetable'
    | '/transport'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AttendanceRoute: typeof AttendanceRoute
  CalendarRoute: typeof CalendarRoute
  CircularsRoute: typeof CircularsRoute
  ClassRoute: typeof ClassRoute
  CoursesRoute: typeof CoursesRoute
  FeesRoute: typeof FeesRoute
  GalleryRoute: typeof GalleryRoute
  HomeworkRoute: typeof HomeworkRoute
  LeaveRoute: typeof LeaveRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TimetableRoute: typeof TimetableRoute
  TransportRoute: typeof TransportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homework': {
      id: '/homework'
      path: '/homework'
      fullPath: '/homework'
      preLoaderRoute: typeof HomeworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class': {
      id: '/class'
      path: '/class'
      fullPath: '/class'
      preLoaderRoute: typeof ClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circulars': {
      id: '/circulars'
      path: '/circulars'
      fullPath: '/circulars'
      preLoaderRoute: typeof CircularsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AiAssistantRoute: AiAssistantRoute,
  AttendanceRoute: AttendanceRoute,
  CalendarRoute: CalendarRoute,
  CircularsRoute: CircularsRoute,
  ClassRoute: ClassRoute,
  CoursesRoute: CoursesRoute,
  FeesRoute: FeesRoute,
  GalleryRoute: GalleryRoute,
  HomeworkRoute: HomeworkRoute,
  LeaveRoute: LeaveRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TimetableRoute: TimetableRoute,
  TransportRoute: TransportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
